import React from 'react';
import { Link } from 'react-router-dom';

const Home = () => {
  return (
    <div className="min-h-screen bg-gradient-to-br from-blue-50 to-green-50">
      {/* Hero Section */}
      <section className="py-12 md:py-20 px-4">
        <div className="max-w-6xl mx-auto text-center">
          {/* Mobile par text size 4xl, laptop par 6xl */}
          <h1 className="text-4xl md:text-6xl font-extrabold text-gray-900 mb-6 leading-tight">
            AI-Powered Personal
            <span className="text-emerald-600 block md:inline"> Diet & Fitness</span> Planner
          </h1>
          
          {/* Mobile par text base, laptop par text-xl */}
          <p className="text-base md:text-xl text-gray-700 mb-10 max-w-3xl mx-auto px-2 font-medium">
            Transform your health journey with personalized diet and workout plans 
            generated by advanced AI. Track your progress, achieve your goals, and 
            maintain a healthier lifestyle.
          </p>

          {/* Buttons: Custom Color & Hover Effects (Same Sizing and Text) */}
          <div className="flex flex-col sm:flex-row gap-4 justify-center items-center">
            <Link 
              to="/signup" 
              className="w-full sm:w-auto bg-emerald-600 text-white px-10 py-4 rounded-xl text-lg font-semibold hover:bg-emerald-500 transition-all shadow-[0_10px_20px_-5px_rgba(5,150,105,0.3)] hover:shadow-[0_15px_25px_-5px_rgba(5,150,105,0.4)] hover:-translate-y-0.5 active:translate-y-0 text-center"
            >
              Get Started
            </Link>

            <Link 
              to="/login" 
              className="w-full sm:w-auto bg-gray-900 text-white px-10 py-4 rounded-xl text-lg font-semibold hover:bg-black transition-all shadow-[0_10px_20px_-5px_rgba(17,24,39,0.3)] hover:shadow-[0_15px_25px_-5px_rgba(0,0,0,0.4)] hover:-translate-y-0.5 active:translate-y-0 text-center"
            >
              Login
            </Link>

            <Link 
              to="/signup" 
              className="w-full sm:w-auto border-2 border-gray-900 text-gray-900 px-10 py-4 rounded-xl text-lg font-semibold hover:bg-emerald-50 hover:border-emerald-600 hover:text-emerald-600 transition-all hover:-translate-y-0.5 active:translate-y-0 text-center"
            >
              Signup
            </Link>
          </div>
        </div>
      </section>

      {/* Features Section */}
      <section className="py-16 px-4 bg-white rounded-t-[3rem] md:rounded-none shadow-inner">
        <div className="max-w-6xl mx-auto">
          <h2 className="text-2xl md:text-4xl font-black text-center text-gray-900 mb-12 uppercase tracking-tight">
            Why Choose Our AI Planner?
          </h2>
          
          {/* Grid: Unchanged Structures with High Contrast Text Enhancements */}
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-8">
            {/* Feature 1 */}
            <div className="group text-center p-8 rounded-2xl bg-gray-50 hover:bg-blue-50 transition-colors border border-transparent hover:border-blue-100">
              <div className="w-16 h-16 bg-blue-100 rounded-2xl flex items-center justify-center mx-auto mb-6 transform group-hover:rotate-6 transition-transform">
                <svg className="w-8 h-8 text-blue-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9.663 17h4.673M12 3v1m6.364 1.636l-.707.707M21 12h-1M4 12H3m3.343-5.657l-.707-.707m2.828 9.9a5 5 0 117.072 0l-.548.547A3.374 3.374 0 0014 18.469V19a2 2 0 11-4 0v-.531c0-.895-.356-1.754-.988-2.386l-.548-.547z" />
                </svg>
              </div>
              <h3 className="text-xl font-extrabold mb-3 text-gray-900">Personalized Plans</h3>
              <p className="text-gray-700 font-medium leading-relaxed">AI-generated diet and workout plans tailored to your specific goals, body type, and preferences.</p>
            </div>

            {/* Feature 2 */}
            <div className="group text-center p-8 rounded-2xl bg-gray-50 hover:bg-green-50 transition-colors border border-transparent hover:border-green-100">
              <div className="w-16 h-16 bg-green-100 rounded-2xl flex items-center justify-center mx-auto mb-6 transform group-hover:rotate-6 transition-transform">
                <svg className="w-8 h-8 text-green-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 19v-6a2 2 0 00-2-2H5a2 2 0 00-2 2v6a2 2 0 002 2h2a2 2 0 002-2zm0 0V9a2 2 0 012-2h2a2 2 0 012 2v10m-6 0a2 2 0 002 2h2a2 2 0 002-2m0 0V5a2 2 0 012-2h2a2 2 0 012 2v14a2 2 0 01-2 2h-2a2 2 0 01-2-2z" />
                </svg>
              </div>
              <h3 className="text-xl font-extrabold mb-3 text-gray-900">Progress Tracking</h3>
              <p className="text-gray-700 font-medium leading-relaxed">Visual charts and analytics to monitor your calorie intake, weight changes, and workout progress.</p>
            </div>

            {/* Feature 3 */}
            <div className="group text-center p-8 rounded-2xl bg-gray-50 hover:bg-purple-50 transition-colors border border-transparent hover:border-purple-100 sm:col-span-2 lg:col-span-1">
              <div className="w-16 h-16 bg-purple-100 rounded-2xl flex items-center justify-center mx-auto mb-6 transform group-hover:rotate-6 transition-transform">
                <svg className="w-8 h-8 text-purple-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 10v6m0 0l-3-3m3 3l3-3m2 8H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
                </svg>
              </div>
              <h3 className="text-xl font-extrabold mb-3 text-gray-900">Export & Share</h3>
              <p className="text-gray-700 font-medium leading-relaxed">Download your plans as PDF files and share them with trainers, nutritionists, or friends.</p>
            </div>
          </div>
        </div>
      </section>
    </div>
  );
};

export default Home;